# Generated by Django 3.1.4 on 2021-03-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_categor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categor',
            new_name='category',
        ),
    ]
